-- Create velo
DELIMITER #
CREATE OR REPLACE TRIGGER 
AFTER INSERT ON EMPRUNT FOR EACH ROW
BEGIN
    DECLARE 
        DATE_EMPRUNT DATE;
        KILOMETRAGE_DEP INT;

    SELECT KILOMETRAGE INTO KILOMETRAGE_DEP
    FROM VELO WHERE ID_VELO=NEW.ID_VELO;

    IF KILOMETRAGE_DEP != KILOMETRAGE_DEPART
        UPDATE EMPRUNT
        SET KILOMETRAGE_DEPART=OLD.KILOMETRAGE;
    

-- Create new Station
DELIMITER ##
CREATE
OR REPLACE TRIGGER new_station BEFORE
INSERT
    ON STATION FOR EACH ROW
    BEGIN
UPDATE STATION
SET
    NB_BORNES_DISPO = NB_BORNES
    WHERE ID_STATION=NEW.ID_STATION;

END ## 
DELIMITER ;


 -- 


 -- 


CREATE
OR REPLACE TRIGGER plus_de_place before
insert
    ON VELO FOR EACH ROW 
BEGIN 
    DECLARE nb_velo INT DEFAULT 0;

SELECT
    NB_BORNES_DISPO INTO nb_velo
FROM
    STATION
WHERE
    ID_STATION = NEW.ID_STATION;

IF nb_velo > 0 THEN
UPDATE
    STATION
SET
    NB_BORNES_DISPO = nb_velo - 1
WHERE
    ID_STATION = NEW.ID_STATION;
ELSE 
    SIGNAL SQLSTATE '45000' SET MYSQL_ERRNO = 30001, MESSAGE_TEXT="PAS DE PLACE CONNARD";
END IF;

END $
DELIMITER;