CREATE TABLE COMMUNE (
    ID_COMMUNE INT PRIMARY KEY,
    NOM_COMMUNE VARCHAR(20)
);

CREATE TABLE ETAT (
    ID_ETAT INT PRIMARY KEY,
    DESCRIPRION VARCHAR(20)
);

CREATE table ADHERENT (
    ID_ADHERENT INT AUTO_INCREMENT,
    NOM VARCHAR(20),
    PRENOM VARCHAR(20),
    ADRESSE VARCHAR(100),
    COMMUNE INT,
    DATE_ADHESION DATE,
    PRIMARY KEY(ID_ADHERENT),
    FOREIGN KEY (COMMUNE) REFERENCES COMMUNE(ID_COMMUNE)
);

CREATE TABLE STATION (
    ID_STATION INT PRIMARY KEY,
    ADRESSE VARCHAR(100),
    COMMUNE INT,
    NB_BORNES INT,
    NB_BORNES_DISPO INT,
    FOREIGN KEY (COMMUNE) REFERENCES COMMUNE(ID_COMMUNE)
);

CREATE TABLE VELO (
    ID_VELO INT PRIMARY KEY,
    MARQUE VARCHAR(20),
    DATE_MISE_SERVICE DATE,
    KILOMETRAGE INT,
    ETAT INT,
    NIVEAU_BATTERIE INT,
    ID_STATION INT,
    FOREIGN KEY (ID_STATION) REFERENCES STATION(ID_STATION)
);

CREATE TABLE EMPRUNT(
    ID_EMPRUNT INT,
    KILOMETRAGE_DEPART INT,
    HEURE_RENDU DATE DEFAULT NULL,
    HEURE_DEPART DATE,
    ID_ADHERENT INT NOT NULL,
    ID_STATION INT NOT NULL,
    ID_VELO INT NOT NULL,
    FOREIGN KEY (ID_ADHERENT) REFERENCES ADHERENT(ID_ADHERENT),
    FOREIGN KEY (ID_STATION) REFERENCES STATION(ID_STATION),
    FOREIGN KEY (ID_VELO) REFERENCES VELO(ID_VELO)
);

CREATE TABLE DISTANCE(
    ID_STATION1 INT,
    ID_STATION2 INT,
    DISTANCE INT,
    FOREIGN KEY (ID_STATION1) REFERENCES STATION(ID_STATION),
    FOREIGN KEY (ID_STATION2) REFERENCES STATION(ID_STATION),
    PRIMARY KEY (ID_STATION1, ID_STATION2)
);

COMMIT;