
CREAte table ADHERENT {
    ID_ADHERENT INT,
    NOM VARCHAR(20),
    PRENOM VARCHAR(20),
    ADRESSE VARCHAR(100),
    DATE_ADHESION DATE,
    PRIMARY KEY(ID_ADHERENT)
}

CREATE TABLE EMPRUNT{
    ID_EMPRUNT INT,
    KILOMETRAGE_DEPART INT,
    HEURE_RENDU DATE,
    HEURE_DEPART DATE,
    ID_ADHERENT INT,
    ID_STATION INT,
    ID_VELO INT,
    FOREIGN KEY (ID_ADHERENT) REFERENCES ADHERENT(ID_ADHERENT),
    FOREIGN KEY (ID_STATION) REFERENCES STATION(ID_STATION),
    FOREIGN KEY (ID_VELO) REFERENCES VELO(ID_VELO)
}

CREATE TABLE STATION {
    ID_STATION INT PRIMARY KEY,
    ADRESSE VARCHAR(100),
    COMMUNE VARCHAR(20),
    NB_BORNES INT,
    NB_BORNES_DISPO INT
}

CREATE TABLE VELO {
    ID_VELO INT PRIMARY KEY,
    MARQUE VARCHAR(20),
    DATE_MISE_SERVICE DATE,
    KILOMETRAGE INT,
    ETAT INT,
    NIVEAU_BATTERIE INT
    FOREIGN KEY (ETAT) REFERENCES ETAT(ID_ETAT),
    FOREIGN KEY (ID_STATION) REFERENCES STATION(ID_STATION)
}

CREATE TABLE ETAT {
    ID_ETAT INT PRIMARY KEY,
    DESCRIPRION VARCHAR(20)
}