SELECT * FROM STATION WHERE ID_STATION <3;
SELECT * FROM STATION WHERE ID_STATION = 15 OR ID_STATION = 16;
SELECT * FROM EMPRUNT WHERE ID_VELO<3;
SELECT * FROM VELO WHERE ID_VELO<3;
call creation_emprunt(1,1);
call creation_emprunt(2,2);
call distance_station(15,1,50);
call distance_station(16,2,10);
SELECT * FROM STATION WHERE ID_STATION <3;
SELECT * FROM STATION WHERE ID_STATION = 15 OR ID_STATION = 16;
SELECT * FROM EMPRUNT WHERE ID_VELO<3;
SELECT * FROM VELO WHERE ID_VELO<3;
call rendu_emprunt(1,1);
call rendu_emprunt(2,2);
select * from VELO WHERE ID_VELO<3;
SELECT * FROM EMPRUNT WHERE ID_VELO<3;



